export function coinForGraph(){
return ({
    coin:[
        {
            id:"0",
            name:"Bitcoin",
            price:{
                January:"235486",
                February:"201456",
                March:"10245",
                April:"11245",
                May:"26458",
                June:"32564",
                July:"25897",
                August:"45886"
            }
        },
        {
            id:"1",
            name:"Ethereum",
            price:{
                January:"1654",
                February:"1254",
                March:"2456",
                April:"1023",
                May:"1023",
                June:"1345",
                July:"1958",
                August:"1465"
            }
        },
        {
            id:"2",
            name:"Tether",
            price:{
                January:"0.997",
                February:"0.879",
                March:"0.964",
                April:"0.458",
                May:"0.498",
                June:"0.798",
                July:"0.325",
                August:"0.956"
            }
        },
        {
            id:"3",
            name:"USD Coin",
            price:{
                January:"1.45",
                February:"1.98",
                March:"1.56",
                April:"1.78",
                May:"1.45",
                June:"1.32",
                July:"1.24",
                August:"1.65"
            }
        },
        {
            id:"4",
            name:"BNB",
            price:{
                January:"300.1",
                February:"345",
                March:"286",
                April:"345",
                May:"370",
                June:"324",
                July:"315",
                August:"375"
            }
        }
    ]
})}
